### PR TITLE
fix: add a SlabModelFactory so that cobblestone slabs actually have all their blockstates

### LINKED ISSUE #98: Crystal Hollows Slabs always generate as bottom slabs instead of correct top/double variants.
## **Version**
commit a6108f7 of skyocean but it still is an issue after my contribution because I initially found it while playing with my fork

## **Expected Behaviour**
 Block model for slabs has all it's variants and it changes according to it's block state

## **Actual Behaviour**
 Block model for slabs always defaults to bottom model

## **Examples**:
Slab that should be using double model (cobblestone in this case)
Image

Slab that should be using top model (cobblestone_slab_top in this case)
Image

## **Possible Reason?**
I believe this happens because slabs are generated as normal blocks instead of having their own ModelFactory, like stairs or snow. The fix would be to create a dedicated SlabModelFactory.

I already have a working implementation, but it has two drawbacks:

- It generates extra models (e.g., x_slab_double) that are just cube_all with the base block’s texture (e.g., cobblestone_slab_double using textures: "all": "block/cobblestone").

       val textureMapping = TexturedModel.CUBE.get(getBaseBlock(block)).mapping

        val bottomSlab = ModelTemplates.SLAB_BOTTOM.plainVariant(fakeBlock, block, textureMapping)
        val topSlab = ModelTemplates.SLAB_TOP.plainVariant(fakeBlock, block, textureMapping)
        val doubleSlab = ModelTemplates.CUBE_ALL.plainVariant(fakeBlock.withSuffix("_double"), getBaseBlock(block), textureMapping)
        
        MultiVariantGenerator.dispatch(block)
            .with(
                PropertyDispatch.initial(BlockStateProperties.SLAB_TYPE)
                    .select(SlabType.BOTTOM, bottomSlab)
                    .select(SlabType.TOP, topSlab)
                    .select(SlabType.DOUBLE, doubleSlab)
            ).let { modelGenContext.collectState(fakeBlock, it) }
    }`

- The way I fetch the base blocks for each slab feels really verbose.

    Image

like surely there is a better way of doing this that is not just having 62 lines of code for all slabs right?

I can push my implementation to my own fork so that it can be looked at if that is helpful.

### PR DESCRIPTION
**Pull request by JustAlex7473**
idk, pretty much that. fixes #98

same two drawbacks as mentioned before:

- It generates extra models (e.g., x_slab_double) that are just cube_all with the base block’s texture (e.g., cobblestone_slab_double using textures: "all": "block/cobblestone").

       val textureMapping = TexturedModel.CUBE.get(getBaseBlock(block)).mapping

        val bottomSlab = ModelTemplates.SLAB_BOTTOM.plainVariant(fakeBlock, block, textureMapping)
        val topSlab = ModelTemplates.SLAB_TOP.plainVariant(fakeBlock, block, textureMapping)
        val doubleSlab = ModelTemplates.CUBE_ALL.plainVariant(fakeBlock.withSuffix("_double"), getBaseBlock(block), textureMapping)
        
        MultiVariantGenerator.dispatch(block)
            .with(
                PropertyDispatch.initial(BlockStateProperties.SLAB_TYPE)
                    .select(SlabType.BOTTOM, bottomSlab)
                    .select(SlabType.TOP, topSlab)
                    .select(SlabType.DOUBLE, doubleSlab)
            ).let { modelGenContext.collectState(fakeBlock, it) }
    }`

- The way I fetch the base blocks for each slab feels really verbose.

    Image

### CODE REVIEW

File: src/common/data/kotlin/me/owdding/skyocean/datagen/models/factories/SlabModelFactory.kt [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+import net.minecraft.client.data.models.blockstates.PropertyDispatch
+import net.minecraft.client.data.models.model.ModelTemplates
+import net.minecraft.client.data.models.model.TexturedModel
+import net.minecraft.core.Direction
+import net.minecraft.resources.ResourceLocation
+import net.minecraft.world.level.block.Block
+import net.minecraft.world.level.block.Blocks
+import net.minecraft.world.level.block.state.properties.BlockStateProperties
+import net.minecraft.world.level.block.state.properties.SlabType
+import net.minecraft.core.registries.BuiltInRegistries
```
Comment (meowora) [inline src/common/data/kotlin/me/owdding/skyocean/datagen/models/factories/SlabModelFactory.kt:17]: Think you have unused imports

**Review by meowora — CHANGES_REQUESTED** [review]

**Review by meowora — APPROVED** [review]
